name: Deploy to Project Management

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.102' # or the version you're using

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish the project
        run: dotnet publish -c Release -o publish

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: project-management:latest

      - name: Deploy to Project Management
        run: |
          aws lambda create-function --function-name albapro --code ImageUri=project-management:latest --runtime dotnet6 --role arn:aws:iam::767397959578:role/aws-service-role/sso.amazonaws.com/AWSServiceRoleForSSO --handler Web.Controllers.LoginController::Login --timeout 30 --region ap-southeast-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
